car_service/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root "cars#index"
  root to: "problems#home"

  resources :problems#, only: [:index, :show]
  resources :cars#, only: [:index, :show, :new, :update, :edit, :create, :delete]

end

car_service/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

car_service/app/models/car.rb
class Car < ApplicationRecord
  belongs_to :problem
end

car_service/app/models/problem.rb
class Problem < ApplicationRecord
  has_many :cars
end

car_service/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

car_service/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
    @problem_area = Problem.all.map { |problem| problem.problem_title }
  end

  def create
    @car = Car.new(car_params)
    @car.problem = Problem.find_by(problem_title: params[:car][:problem])
    @car.save
    redirect_to cars_path(@car)
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to @car
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  private
  def car_params
    params.require(:car).permit(:year, :make, :model, :mileage, :customer, :customer_statement, :img_url)
  end
end

car_service/app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def home
  end
  
  def index
    @problems = Problem.all
  end

  def show
    @problem = Problem.find(params[:id])
  end
end

car_service/app/helpers/application_helper.rb
module ApplicationHelper
end

car_service/app/views/cars/edit.html.erb
<h1>Edit <%= @car.make %></h1>

<%= form_for @car do |f| %>
  <h4><%= f.label :customer %></h4>
  <%= f.text_field :customer %>
  <br>
  <h4><%= f.label :customer_statement %></h4>
  <%= f.text_field :customer_statement %>
  <br>
  <h4><%= f.label :mileage %></h4>
  <%= f.text_field :mileage %>
  <br>
  <br>
  <%= f.submit %>

<% end %>
<br>

<%= form_for @car, method: :delete do |f| %>
  <%= f.submit "Delete", class: "delete" %>
<% end %>

car_service/app/views/cars/index.html.erb
<h1>Vehicles</h1>
<% @cars.each do |car| %>
  <div>
    <h2><a href='<%= car_path(car) %>'><%=car.year%> <%=car.make%> <%=car.model%></a> - <%= car.problem.problem_title %></h2>
  </div>
<% end %>

car_service/app/views/cars/new.html.erb
<h1>New Vehicle Entry</h1>

<%= form_for @car do |f| %>
  <h4><%= f.label :customer %></h4>
  <%= f.text_field :customer %>
  <br>
  <h4><%= f.label :customer_statement %></h4>
  <%= f.text_field :customer_statement %>
  <br>
  <h4><%= f.label :year %></h4>
  <%= f.text_field :year %>
  <br>
  <h4><%= f.label :make %></h4>
  <%= f.text_field :make %>
  <br>
  <h4><%= f.label :model %></h4>
  <%= f.text_field :model %>
  <br>
  <h4><%= f.label :mileage %></h4>
  <%= f.text_field :mileage %>
  <br>
  <h4><%= f.label :img_url %></h4>
  <%= f.text_field :img_url %>
  <br>
  <br>
  <%= f.select(:problem, options_for_select(@problem_area)) %>
  <br>
  <br>
  <%= f.submit %>

<% end %>

car_service/app/views/cars/show.html.erb
<h1><%= @car.year %> <%= @car.make %> <%= @car.model %></h1>
<h2>Mileage: <%= @car.mileage %> miles</h2>
<h2>Vehicle Owner: <%= @car.customer %></h2>
<h2>Problem: <%= @car.customer_statement %></h2>

<div class="car">
  <img class="car_img" src="<%= @car.img_url %>">
</div>
<h3><a href="/cars/<%= @car.id %>/edit">Update Vehicle Info</a> </h3>

car_service/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarService</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <h2><%= link_to "Home", root_path %> | <%= link_to "Categories", problems_path %> | <%= link_to "View Vehicles", cars_path %> | <%= link_to "New Vehicle", new_car_path %></h2>

    <%= yield %>
  </body>
</html>

car_service/app/views/problems/home.html.erb
<img class = "logo" src="http://bit.ly/2lCRHd4">

car_service/app/views/problems/index.html.erb
<h1>Categories</h1>
<% @problems.each do |issue| %>
  <div class="problem">
    <a href="<%= problem_path(issue) %>">
      <h2><%= issue.problem_title %></h2>
      <img src="<%= issue.img_url %>">
    </a>
  </div>
<% end %>

car_service/app/views/problems/show.html.erb
<h1><%= @problem.problem_title %></h1>
<% @problem.cars.each do |car| %>
  <div class="car">
    <h2><a href='<%= car_path(car) %>'><%=car.year%> <%=car.make%> <%=car.model%></a></h2>
  </div>
  </div>
<% end %>